
server:
  port: 81
  max-http-header-size: 102400
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://81.69.247.142/baiduFace?useSSL=false&serverTimezone=UTC
    username: root
    password: root
  mvc:
    view:
      suffix: .html
  redis:
    # 地址
    host: 124.223.207.183
    # 端口，默认为6379
    port: 6379
    # 数据库索引
    database: 0
    # 密码
    password: root
    # 连接超时时间
    timeout: 10s
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池的最大数据库连接数
        max-active: 8
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
#  resources:
#    add-mappings: true        # 静态资源默认配置规则是否开启,false表示禁用
#    cache:
#      period: 10000 # 秒级的缓存，以缓存的形式来访问服务器
#    static-locations: [classpath:/abc/,] 静态资源访问路径
#  mvc:
#    static-path-pattern: /xxx/**  静态资源访问前缀，不过会让welcome和favicon失效

# 配置mybatis规则
mybatis:
 # config-location: classpath:mybatis/mybatis-config.xml  # 不能跟configuration同时存在
  mapper-locations: classpath:mybatis/mapper/*.xml
  #开启驼峰命名识别
#  configuration:
#    map-underscore-to-camel-case: true